version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: latest
        PHX_VERSION: 1.5.3
    volumes:
      - ..:/workspace:cached
      - vscode-extension:/root/.vscode-server-insiders
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: my_app_dev

volumes:
  postgres-data:
  vscode-extension: